name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
        # architecture: [x64, arm64]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # 添加architecture参数用于设置Node.js的架构
        architecture: ${{ matrix.architecture }}

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Package Binary
      run: npm pack

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.architecture }}-node-${{ matrix.node-version }}
        path: |
          ./build/Release/*.node
          ./*.tgz

